### PR TITLE
Add nautil.us

### LINKED ISSUE #283: Add Nautilus
[Nautilus](http://nautil.us/) is a very cool website I would like to have added

### PR DESCRIPTION
**Pull request by wernychory**
Closes #283

### CODE REVIEW

**Comment by iamadamdev** [comment]
Please also add to README.md and options.js

**Comment by iamadamdev** [comment]
Closed in favor of using Cookie Remover

**Comment by pulmuxd** [comment]
In my opinion, Cookie Remover is not a real alternative. The whole point of using a browser extension like this is to automate stuff so that I don't have to manually click a button and reload the whole page after reading two articles.

**Comment by iamadamdev** [comment]
@pulmuxd Then please also add to README.md and options.js if you want this PR merged

**Comment by iamadamdev** [comment]
Please fix merge conflicts

**Pull request closed without merging**
