### PR TITLE
Switch from <all_urls> to per-site permissions in manifest.json

### PR DESCRIPTION
**Pull request by TheGoddessInari**
#171 mentions being too lazy to add everything to the permissions array, so this should take care of it.

### CODE REVIEW

**Comment by iamadamdev** [comment]
The problem with this is it just increased the overhead to add a new site. There are now 4 places (background, options, readme, manifest) you need to add the same site and thus increased chances for bugs.

**Comment by TheGoddessInari** [comment]
Problems like that should be evident from the diffs and most people are going to be suspicious when it asks for all sites but only works on the listed ones.

Perhaps a pre-commit hook to see if the other three files have names in them matching the first? I'm sure there's a better way to do it, but that'd keep the most basic of errors from getting committed by accident.

**Comment by zardus** [comment]
Please consider merging this. Security-conscious users aren't going to install an extension that asks for ultimate access on all sites, but we'd really like to be able to use this awesome extension.

**Comment by iamadamdev** [comment]
If you update with the latest sites I will merge this.

**Comment by TheGoddessInari** [comment]
The latest sites? Unless I missed one, it's been current with `master` since the initial PR.

**Comment by iamadamdev** [comment]
I added a removed some sites, please pull latest master.
https://github.com/iamadamdev/bypass-paywalls-firefox/releases

**Comment by TheGoddessInari** [comment]
Right...are you getting confused that the Chrome version was updated more recently than the Firefox version?
The code between the two is mostly the same, are you sure they can't be combined like most webextensions?

Because this PR has always been current against the `master` in **this** tree.

```
* 340c4be - (HEAD -> granular-permissions, origin/granular-permissions) Switch from <all_urls> to per-site permissions. (4 weeks ago) <TheGoddessInari>
* b16c802 - (tag: v1.5.3, upstream/master, origin/master, master) Fix theaustralian.com.au (4 weeks ago) <Adam>
```

**Comment by iamadamdev** [comment]
I just did a quick search and didn't see telegraph in your diff so that's why I thought some sites were missing.

**Comment by iamadamdev** [comment]
The JS can most likely be combined but the update mechanism for Chrome and Firefox are different.

**Comment by TheGoddessInari** [comment]
Looks like `defaultSites` is defined multiple times, and `telegraph.co.uk` was the only one not defined in background.js.

**Comment by GauthierPLM** [comment]
As said before, merging this would make the extension seen as more secure by users.
Access to all websites is a bad practice unless you really need access to all websites. A small guide/PR template to remind users to add the website to the right places should be enough and would avoid the extension from accessing all websites while it only needs to access a small part of them.

**Comment by iamadamdev** [comment]
I don't see where `defaultSites` is defined multiple times? I will merge this before the next release.

**Pull request merged**
